if [ -f `brew --prefix`/etc/bash_completion.d/git-flow-completion.sh ]; then
    . `brew --prefix`/etc/bash_completion.d/git-flow-completion.sh
fi

export NVM_DIR=~/.nvm
. $(brew --prefix nvm)/nvm.sh

if [ -a ${HOME}/.bash_aliases ]; then
  . ${HOME}/.bash_aliases
fi

if [ -a ${HOME}/.bash_spacemonkey ]; then
  . ${HOME}/.bash_spacemonkey
fi

export PIP_REQUIRE_VIRTUALENV=true
export DEFAULT_VIRTUALENV_DIR="${HOME}/.virtualenvs"

gpip(){
  PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

vpee(){
  if [ -n "$1" ] && [ -f "${DEFAULT_VIRTUALENV_DIR}/$1/bin/activate" ]; then
    source ${DEFAULT_VIRTUALENV_DIR}/$1/bin/activate 
  else
    echo "Requires the name of the virtual enviornment and for the virtual enviornment to exists"
  fi
}

alias workoff='deactivate'

export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

PATH=${HOME}/.cargo/bin:${PATH}

export PS1="\H@\w :> "
