(source gnu)
(source melpa)

(depends-on "powerline")
(depends-on "labburn-theme")

(depends-on "exec-path-from-shell")
(depends-on "evil")
(depends-on "evil-leader")

(depends-on "company")
(depends-on "company-quickhelp")
(depends-on "flycheck")

(depends-on "go-mode")
(depends-on "go-eldoc")
(depends-on "company-go")

(depends-on "web-mode")
(depends-on "tide")

(depends-on "ag")
(depends-on "markdown-mode")
