alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias h='history'
alias ..='cd ..'
alias ...='cd .. && cd ..'
alias ....='cd .. && cd .. && cd ..'
alias please='sudo'
alias plz='sudo !!'
alias simonsays='sudo'
alias irb='irb --readline -r irb/completion'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -alh --color=auto'
alias tp="trash-put"
alias tl="trash-list"